services:
  - type: web
    name: resumeiq
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    runtime: python
    runtimeVersion: 3.10.13